//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogFetchApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogFetchApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string Btn_Fetch {
            get {
                return ResourceManager.GetString("Btn_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Btn_Previous {
            get {
                return ResourceManager.GetString("Btn_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  English.
        /// </summary>
        public static string Menu_English {
            get {
                return ResourceManager.GetString("Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francais.
        /// </summary>
        public static string Menu_French {
            get {
                return ResourceManager.GetString("Menu_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu_Header {
            get {
                return ResourceManager.GetString("Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will stay like before .
        /// </summary>
        public static string Msg_Nevermind {
            get {
                return ResourceManager.GetString("Msg_Nevermind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the changes you need to restart.
        /// </summary>
        public static string Msg_Restart {
            get {
                return ResourceManager.GetString("Msg_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to restart manually when ready.
        /// </summary>
        public static string Msg_RestartLater {
            get {
                return ResourceManager.GetString("Msg_RestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed.
        /// </summary>
        public static string Text_Breed_Choice {
            get {
                return ResourceManager.GetString("Text_Breed_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Image  .
        /// </summary>
        public static string Text_NbImage {
            get {
                return ResourceManager.GetString("Text_NbImage", resourceCulture);
            }
        }
    }
}
